### ISSUE TITLE
Comchap/Comcut update script

### ISSUE THREAD

**Issue by BrettSheleski** [mjbrowns/plexpost#2]
I noticed that the `update-sources` script downloads comchap and comcut script files directly from Github using the following.

```
echo Updating comchap
curl https://raw.githubusercontent.com/BrettSheleski/comchap/master/comchap > ${SRCBIN}/comchap
curl https://raw.githubusercontent.com/BrettSheleski/comchap/master/comcut > ${SRCBIN}/comcut
chmod 755 ${SRCBIN}/comchap
chmod 755 ${SRCBIN}/comcut
```

I would prefer (being the comchap/comcut author) that instead of downloading the individual files from Github that it would clone the entire Comchap repository instead.  This may introduce another dependency in your project to git itself, but I think that that would be acceptable.

Doing so this way should also help protect your script from any future updates/refactorings I may do to comchap/comcut.  Seeing as the two scripts are largely very similar, I already have somewhat of a plan to refactor the code and push all commonalities into a third file that both comchap and comcut scripts would reference internally.  If you are pulling the comchap/comcut script files directly from Github, then it obviously would not get this other file and therefore lead to a broken comchap/comcut installation.

I think doing so should also make it so you don't have to chmod the comchap/comcut scripts after retrieving them either.

You could update your script to something like the following:
```
if [ -d "$comchapDir" ]; then
  # update existing git comchap repo
  git -C "$comchapDir" pull
else
  #clone comchap
  git -C "$comchapDir" clone https://github.com/BrettSheleski/comchap.git
fi
```

There's also a Makefile in the comchap repo as well.  I basically just use the Makefile to move the scripts to the /usr/local/bin directory so I can call the scripts without needing to supply the full path on my system.  One thing I think may be helpful for you would be to have a `make update` option added to the Makefile which would update the comchap repo using git.  I could also see providing a way to specify the output directory in a `make install` call as well.  I'm open to suggestions (and/or pull requests) here.

**Comment by mjbrowns** [comment]
This is very helpful!  I've redone the update-sources script to do a git clone and make install per your request.

Due to the way my build setup works (if you aren't familiar with docker this may be a little weird), the builds are done in a two-step process.  First, update-sources runs.  This gathers all the sources and puts them into a directory structure called src under my git repo.  The processes that do the component builds and install them are running as root inside the containers, which is why I have to fiddle with ownership and permissions since the src directory is owned by my non-root account.  

The build script assembles the actual docker container that then gets published.

Either way, this is a better solution than the one I had before.  As long as you don't introduce any required paths in the make install process that are outside of /usr/local this process should work fine, even if you reorganize the code.

One thing to note - your makefile ln -s to put the links in /usr/local/bin should be an ln -sf; I've worked around that by manually removing the link before I start the builds, but I believe it would be best practice to use -sf, or to have the makefile remove old links.

**Comment by BrettSheleski** [comment]
I'll update my Makefile per your recommendation.  I always did a `make clean` before doing another `make install` so I haven't come across issues.

**Comment by mjbrowns** [comment]
That's probably best practice.  I just completely reorganized how the files are laid out in my github project and rewrote the update-sources to completely build the file tree from scratch from original sources; it should be more reliable and it now conforms to your methodology above.

Since I'm now starting with a fresh working tree every time I won't run into the make clean issue anyway.
