### ISSUE TITLE
Inflexibility with docker container

### ISSUE THREAD

**Issue by simora** [mjbrowns/plexpost#3]
I want to be able to change the handbrake cli options but that isn't possible with any measure of ease. Move the scripts out of the image and place all the scripts into a root folder in the root of the docker source directory. add the following to your Dockerfile:

COPY root/ /

This will simplify your docker image creation and permit more flexible updates and usage.

Refer to the following docker project for usage of the copy root/ design choice.

https://github.com/linuxserver/docker-plex

**Comment by simora** [comment]
I'm trying to move some of the files around to acheive a copy root / design but i can't find your tinycgi src's.

They are referenced here in your build-sources script but the files do no exist. They are in your image. Did you put them into your local source tree and forget to add the new files to the commit?

https://github.com/mjbrowns/plexpost/blame/master/build-sources#L94

**Comment by mjbrowns** [comment]
My apologies but I am very busy this week and will not likely be able to address these issues before next week.

I do see the copy root model and I like it.  However, because of the way I'm doing my build model it will take a bit to revamp it all.

As you can imagine, this project has evolved a lot from when I first put it together and there are quite a few things I would do differently were I to start over.

I like the idea of providing an easy way for people to customize the handbrake options but tbh I'm almost at the point of just doing it all in ffmpeg and eliminating hbcli altogether.  However I've found that some of the TV stations are weirdly inconsistent in their audio channel markup and ordering, and initially handbrake did a great job of sorting all that out.

More of a priority though will be creating a detection algorithm so users can create custom comskip.ini files based on the show name as I've found that while specific shows/channels can be very well tuned, I've not found a single comskip.ini that works well with everything.

I appreciate your suggestions and I can very easily make the handbrake options a dockerfile environment variable.  Before I do that, though, would it be more valuable to have show specific settings?  What other show specific settings do you think would be valuable?  Would you value the ability to have the lightweight web UI control those settings as well?

**Comment by Unkas** [comment]
Hi, I have actually been working on something that uses mjbrowns queueing code to queue up video files for transcoding.  I replaced the HBCLI with donmelton's transcode-video.  I have also stripped out the comskip for now until I learn more about it.  I also removed the need to build the image yourself and you can just pull it down directly from hub.docker and start using it.  I hope you don't mind that I copied your scripts since I'm new to shell and didn't want to reinvent the wheel, plus I didn't see anything I could change.

simora: if you have an idea of how you would like to include custom Handbrake lines let me know.  It is still being developed and I need to write up a better Readme.
[My Project](https://github.com/Unkas/PlexPostTranscode)

**Comment by mjbrowns** [comment]
Custom handbrake lines will be easy.  Hopefully I can get to it this weekend.

Unkas, I have this built already and have it published on Dockerhub and have from the beginning. I don't mind you copying my stuff but I did check with the comskip and comcut owners for permission to distribute on dockerhub.  They also requested that I provide automatic pull-from-source capabilities for those components in my source, which is why I did it the way I did.

See https://hub.docker.com/r/mbrown/plexpost/

**Comment by simora** [comment]
My thought was to have everything that isn't built, ie the entire src folder of mjbrowns repo copied into the docker container via the dockerfile. This would allow someone who knows what they are doing to be able to change the handbrake cli options. The built source and the cgi bits are baked into the docker image but the scripts can be outside the image and copied into the docker container. I don't know what other practical use you can gain from having them copied into the container but having baked into the image makes it too difficult to change.

I thought a docker variable might work too but i think that would be too cumbersome and ultimately the files shouldn't be baked into the image anyways.

**Comment by mjbrowns** [comment]
@simora 

Either I am not understanding what you are saying, or you seem to have a misperception about how docker images work and are created.  If we use the copy /root / model as you suggest, all those files go into the docker image.  They are always baked into the image - that's what the dockerfile specifies.  Now, in terms of customization - I've put all the binaries in /usr/local/bin, and i don't think there was anything there before I started.  So, if you use my published build, or build your own image from the dockerfile is immaterial.  There are a couple of ways you could customize what I'm doing to your own liking.

Method 1: Dockerfile:
from mbrown/plexpost
copy <your custom file> /usr/local/bin/

Method 2: filesystem maps
docker pull mbrown/plexpost
docker run -itd mbrown/plexpost --name plexpost
docker stop plexpost
docker cp plexpost:/usr/local/bin/* ./mybins
docker rm plexpost
docker run -itd mbrown/plexpost --name plexpost -v ./mybins:/usr/local/bin

Basically this will allow you to edit the files in /usr/local/bin however you want.  its great for data mapping of course and its pretty good for testing, but for long term use, method 1 is the best way to customize what I've done.

I understand that the build model i'm using isn't terribly efficient, but I have been using this project to learn lots of different things along the way.  Naturally I'd like to go back and reorganize it (and I will) but that will take some time.  Besides, it basically works, and I'm more focused on some bugfixes and additional feature support and customization before I completely redo it.

Docker variables will work just fine for handbrake customization.  I just have to write it in.  It won't take too long once I get to i, but as I said, unfortunately RL is really busy right now - and I think it will work better if I actually put all that stuff into my little management portal.

I'm actually thinking of setting up a set of filters using a list of regexp matches on a priority order that would enable custom settings for matched sets. Think of it this way:

If showname matches "NCIS", you would have the following options:
* Transcode on/off
* Transcode settings (via either options or a customizable cli string, but that might be dangerous)
* Custom comskip.ini
* comclean on/off (remove commercials versus just mark them)

I appreciate the suggestions and so far I plan to get to all of these, but again...please be patient, this is a side project for me.

**Comment by mjbrowns** [comment]
Ok, so I dug into all this today and I've completely rewritten the build process.  Some things you need to understand:

* To avoid having all the build tools on my servers, I use a container that I create where all the build tools and languages I need are installed and ready/easy to use.  I hadn't included that container previously, but now I've incorporated it into the build process.
* The entire build process is now done with a Makefile.  I'm not a Makefile pro, so I'm sure there are lots of ways I could optimize it (**feel free to make suggestions**).  
* The authors of comskip and comchap both asked me to create a process that would pull sources from their repositories instead of redistributing a potentially older version of their codebase.  
* The makefile process now builds a workdir tree that holds the overlays to the root directory structure of the container.  Using this process, the makefile will essentially auto-update s6, comskip, comchap, tinycgi, and slackpost from their respective sources.
* The scripts that form the core of this project are still in the src directory but they are, per @simora's suggestion, laid out in the filesystem hierarchy for ease of customization.

Scripts and the auto-built components are loaded into the container image using the docker ADD primitive:
```
ADD workdir /
ADD src /
```

Thus, if you want to customize my stuff, you can checkout/clone/fork my repo and simply modify the scripts in the src tree, then make and your own version of the container should be completely built.

Since this addresses the original request in this thread I'm closing it.  I do plan to add my own handbrake customizations but that may be some time out, so in the meantime, happy customizing with your own version.
